[Generic Simulation Settings]
dymola_simulation = False
create_external_elements = False
max_wall_thickness = 0.3
group_unidentified = fuzzy
fuzzy_threshold = 0.7
reset_guids = False
weather_file_path = None
add_space_boundaries = False
correct_space_boundaries = False
close_space_boundary_gaps = False

[EnergyPlusSimSettings]
cfd_export = False
split_bounds = False
add_shadings = True
split_shadings = False
run_full_simulation = False
ep_version = 9-4-0
ep_install_path = \usr\local\EnergyPlus-9-4-0
system_sizing = True
run_for_sizing_periods = False
run_for_weather_period = True
solar_distribution = FullExterior
add_window_shading = None
output_format = CommaAndHTML
unit_conversion = JtoKWH
output_keys = ['output_outdoor_conditions', 'output_zone_temperature', 'output_zone', 'output_infiltration', 'output_meters']
correct_space_boundaries = True
close_space_boundary_gaps = True
add_natural_ventilation = True

[PlantSimSettings]
aggregations = ['UnderfloorHeating', 'PipeStrand', 'Consumer', 'ParallelPump', 'ConsumerHeatingDistributorModule', 'GeneratorOneFluid']
tolerance_connect_by_position = 10

[BuildingSimSettings]
layers_and_materials = LOD.low
construction_class_walls = heavy
year_of_construction_overwrite = None
construction_class_windows = Alu- oder Stahlfenster, Waermeschutzverglasung, zweifach
heating = True
cooling = False
deactivate_ahu = False
prj_use_conditions = None
prj_custom_usages = None
setpoints_from_template = False
sim_results = ['heat_demand_total', 'cool_demand_total', 'heat_demand_rooms', 'cool_demand_rooms', 'heat_energy_total', 'cool_energy_total', 'heat_energy_rooms', 'cool_energy_rooms', 'air_temp_out', 'operative_temp_rooms', 'air_temp_rooms', 'internal_gains_machines_rooms', 'internal_gains_persons_rooms', 'internal_gains_lights_rooms', 'n_persons_rooms', 'infiltration_rooms', 'mech_ventilation_rooms', 'heat_set_rooms', 'cool_set_rooms']
add_space_boundaries = True
correct_space_boundaries = False
split_bounds = False
add_shadings = False
split_shadings = False
close_space_boundary_gaps = False
fix_type_mismatches_with_sb = True
create_plots = False
set_run_period = False
run_period_start_month = 1
run_period_start_day = 1
run_period_end_month = 12
run_period_end_day = 31
plot_singe_zone_guid = 
overwrite_ahu_by_settings = True
ahu_heating = False
ahu_cooling = False
ahu_dehumidification = False
ahu_humidification = False
ahu_heat_recovery = False
ahu_heat_recovery_efficiency = 0.65

[Backend]
use = energyplus

[Frontend]
use = ConsoleFrontEnd

[Modelica]
version = 4.0

